version: '3.9'

services:
  ###############################################################################
  # Portainer agents that collect information from nodes
  ###############################################################################
  agent:
    image: portainer/agent:2.14.2-alpine
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
      # - bocraswarm
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
  ###############################################################################
  # The main portainer that processes and does visualization of information
  ###############################################################################
  portainer:
    image: portainer/portainer-ce:2.14.2-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - ${ROGUE_ERP_DATA}/portainer:/data
    networks:
      - agent-network
      - rogueerp-public
      #- bocraswarm
    deploy:
      mode: global
      placement:
        constraints:
          #- node.role == manager
          #- node.labels.prim1 == true
          - node.labels.rogueerp_portainer == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=rogueerp-public
        - traefik.constraint-label=rogueerp-public
        - traefik.http.routers.portainer-https.rule=Host(`${PORTAINER_DOMAIN}`)
        - traefik.http.routers.portainer-https.entrypoints=${ACTIVE_ROUTER_ENTRY}
        - traefik.http.routers.portainer-https.tls=${SSL_SECURE}
        #- traefik.http.routers.portainer-https.tls.certresolver=le
        - traefik.backend.loadbalancer.swarm=true
        - traefik.backend.loadbalancer.stickiness=true
        - traefik.http.services.portainer.loadbalancer.server.port=9000

###############################################################################
# Networks
###############################################################################

networks:
  agent-network:
    attachable: true
  rogueerp-public:
    external: true
