version: "3.9"
services:
  ###############################################################################
  # Postgres database
  ###############################################################################
  db:
    hostname: db
    image: bitnami/postgresql:15
    volumes:
      - ${ROGUE_ERP_DATA}/db/pgdata:/bitnami/postgresql
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      TZ: Africa/Gaborone
    # depends_on:
    #   proxy:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "--username=postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      traefik-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.bocra-db.entrypoints=${ACTIVE_ROUTER_ENTRY}"
        - "traefik.http.routers.bocra-db.rule=Host(`${DB_DOMAIN}`)"
        - "traefik.http.routers.bocra-db.tls=${SSL_SECURE}"
        - "traefik.http.routers.bocra-db.tls.certresolver=le"
        - "traefik.http.services.bocra-db.loadbalancer.server.port=5432"

  ###############################################################################
  # Postgres administration frontend
  ###############################################################################
  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:6.18
    networks:
      traefik-public:
    # depends_on:
      # proxy:
      #   condition: service_healthy
      # db:
      #  condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
      TZ: Africa/Gaborone
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.bocraportal_proxy == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.bocra-pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.bocra-pgadmin.entrypoints=${ACTIVE_ROUTER_ENTRY}"
        - "traefik.http.routers.bocra-pgadmin.rule=Host(`${DB_DOMAIN}`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.bocra-pgadmin.tls=${SSL_SECURE}"
        - "traefik.http.routers.bocra-pgadmin.tls.certresolver=le"

###############################################################################
# Networks
###############################################################################
networks:
  rogueerp-public:
    external: true
